# Generated by Django 2.2.3 on 2019-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxid', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=128)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('wxid', models.CharField(max_length=32)),
                ('driver', models.CharField(max_length=128)),
                ('driving', models.CharField(max_length=128)),
            ],
        ),
    ]
